package codevalueclass;

import java.util.ArrayList;
import java.util.List;

public class AddTCode {
	public static TCodeClass addNewTCode(int Number, String TCodeString, String SystemName,
			String FunctionDescription) {
		TCodeClass NewTCode = new TCodeClass(Number, TCodeString, SystemName, FunctionDescription);
		return NewTCode;
	}

	public static List<TCodeClass> addTCode() {
		List<TCodeClass> TCodeList = new ArrayList<>();

		// Variable Order: TCode; System; Description;
		int num = 0;
		TCodeClass NO1 = new TCodeClass();
		NO1 = addNewTCode(num++, "me33k", "ECC", "Display Contract");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "sm37", "EBP", "Simple Job Selection; Check Mass Upload Process");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "we02", "ECC", "IDOC List; Check IDOC info");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "we20", "ECC", "Partner Profile; IDOC config");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me23n", "ECC", "Display Purchase Order");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me80fn", "ECC", "General Evaluations;Check Purchase Order/Contract/SA and so on Info");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zerm_mmp002", "SECC", "Mass Upload PO; Create Purchase Order");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me31k", "ECC", "Create Contract");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me32k", "ECC", "Change Contract; Edit Contract");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "spro", "SECC", "Customizing: Execute Project; Looking For Factory and Company Orgnization Structure");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me21", "SECC", "Create Purchase Order: Initial Screen");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "su3", "Any", "Maintain UserProfile; Preference; Setting");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me01", "ECC", "Maintain Source List; Create;");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me03", "ECC", "Display Source List; Material; Plant");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "xk01", "ECC", "Create Vendor");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "xk02", "ECC", "Change Vendor");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "xk03", "ECC", "Display Vendor");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zerm_sp001", "ECC", "SPM Plan Order Split/Download/Upload");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zerm_sp002", "ECC", "SPM Order Dispatch Cancellation");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zerm_sp009", "ECC",
				"Automation Generate Plan Order/PR; SPM Order Dispatch Cancellation");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zmmr0009", "ECC", "WW Hub 补货到哥伦比亚流程SO创建IDOC报错");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zerm_sp009", "ECC",
				"Automation Generate Plan Order/PR; SPM Order Dispatch Cancellation");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERM_MMPP066", "ECC", "Mass upload HTS code (commodity code)");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ME57", "ECC", "Assign and Process Purchase Requisitions");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERD_MMPP189", "ECC", "PR/PO GR Information to PTC");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERD_MMPP191", "ECC", "Send outbound STOPRDPRSO to DPE");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERD_MMPP099", "ECC", "PO DeliveryInformation to 3PL");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "AL11", "ECC", "SAP Directories");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERD_MMPP184", "ECC", "Send PO/GR/IV Information to FTP");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERM_MMPP100", "ECC", "Change/Display View \"Maintian Mail Address\"：Overview");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZJDMMPP023", "ECC", "Reverse GR and IV document");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "MIRO", "ECC", "IV");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ME59N", "ECC", "Automatic Creation of Purchase Order from Requisitions; Create PO");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERM_MMPP110", "ECC", "Mass create info record");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZTR", "ECC", "");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERM_MMPP088", "ECC", "PTC trigger PR log and Reprocess falled PR");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERD_MMP003", "ECC", "send PO information to 3PL");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERD_MMPP091", "ECC", "PO Tracing Report");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "SU53", "ECC", "Display Authorization Data for User ZHUPR1");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "VL32N", "ECC", "Change Inbound Delivery");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "mb1c", "ECC", "Add Stock");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "se93", "SECC", "");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERM_MMP001", "SECC", "Create inbound delivery from Core ECC");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERD_MMP001", "SECC", "Send PO Information to SPP via FTP");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERM_MMP_STKCHK", "SECC", "STO Stock Check");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERD_MM_POMATCH", "SECC", "");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZMMR0001", "SECC", "Display sub PO data and re-process");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERD_MMP003", "SECC", "Blocked STO substitution report");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZMMR0002", "SECC", "");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZMMR0005", "SECC", "Replenishment E2E report");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ZERM_MM005", "SECC", "MBG create STO");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "ST22", "EBP", "ABAP Runtime Errors; Dump Display");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "pposa_bbp", "EBP", "General Attributes(EBP) Display; Assign to Company");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "se37", "EBP", "Function Builder; ABAP");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "se91", "EBP", "Message Maintenance; ABAP");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "se80", "EBP", "Object Navigator; ABAP");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "se11", "EBP", "ABAP Dictionary");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me22n", "ECC", "Edit PO");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me51n", "ECC", "PR Creation");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me59n", "ECC", "PR Convert PO");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me29n", "ECC", "PO Release");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "bp", "Any", "Business Partner");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zmme0052", "ECC", "Not load yet;");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zerm_mmpp009", "", "PR Convert PO");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zerm_mmp011", "", "mass create PR");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "zerd_mmpp038", "", "pr list");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "xk03", "ECC", "Display vendor master");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me33l", "ECC", "Display SA");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "se38", "ECC", "ABAP Editor; check program");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "migo", "ECC", "Create PO GR");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "se38", "ECC", "run program");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "mr8m", "ECC", "credit memo");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "se37", "ECC", "Display function module; FM");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "spro", "ECC", "Purchase Org etc. configuration");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me03", "ECC", "Material Master");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "me53n", "ECC", "Display PR");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "commpr01", "EBP", "Display Product");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "mbst", "ECC", "Cancel Materia Documents; Cancel GR");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "sxmb_moni", "EBP;SUS", "Monitor for XML process");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "bbp_pd", "EBP;SUS", "Display documents; PO, shopping cart, etc..");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "bd87", "ECC", "Drop IDOC");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "", "", "");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "", "", "");
		TCodeList.add(NO1);
		NO1 = addNewTCode(num++, "", "", "");
		TCodeList.add(NO1);
		
		
		

		return TCodeList;
	}
}
